# 1. Use lightweight python base
FROM python:3.12-slim

# 2. Set working directory inside /app
WORKDIR /app

# 3. Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpoppler-dev \
    libopenblas-dev \ 
    && rm -rf /var/lib/apt/lists/*


    # Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"
COPY pyproject.toml /app
RUN uv sync

# 6. Expose Gradio default port
EXPOSE 7860

# 7. Run app
CMD ["bash"]
